## Global Historical Climatology Network Dataset
Variables are stored in both rows and columns
This dataset represents the daily weather records for a weather station (MX17004) in Mexico for five months in 2010.

In [1]:
# Import libraries needed

import pandas as pd

In [2]:
# Open the csv file

weather = pd.read_csv('weather-raw.csv')

In [3]:
# Have a look on the data set: 
# 1) The Id is the station name = MX17004 (the same for all the values) so this column is not relevant
# 2) the columns d1 - d31 are the days and there are many NaN
# 3) tmax and tmin should be columns and there should be a column called days containing the day numbers

weather

,id,year,month,element,d1,d2,d3,d4,d5,d6,...,d22,d23,d24,d25,d26,d27,d28,d29,d30,d31
0,MX17004,2010,1,tmax,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.8,NaN
1,MX17004,2010,1,tmin,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.5,NaN
2,MX17004,2010,2,tmax,NaN,27.3,24.1,NaN,NaN,NaN,...,NaN,29.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,MX17004,2010,2,tmin,NaN,14.4,14.4,NaN,NaN,NaN,...,NaN,10.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,MX17004,2010,3,tmax,NaN,NaN,NaN,NaN,32.1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,MX17004,2010,3,tmin,NaN,NaN,NaN,NaN,14.2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,MX17004,2010,4,tmax,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,36.3,NaN,NaN,NaN,NaN
7,MX17004,2010,4,tmin,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,16.7,NaN,NaN,NaN,NaN
8,MX17004,2010,5,tmax,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,33.2,NaN,NaN,NaN,NaN
9,MX17004,2010,5,tmin,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,18.2,NaN,NaN,NaN,NaN
10,MX17004,2010,6,tmax,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.1,NaN,NaN
11,MX17004,2010,6,tmin,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.0,NaN,NaN
12,MX17004,2010,7,tmax,NaN,NaN,28.6,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,MX17004,2010,7,tmin,NaN,NaN,17.5,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,MX17004,2010,8,tmax,NaN,NaN,NaN,NaN,29.6,NaN,...,NaN,26.4,NaN,29.7,NaN,NaN,NaN,28.0,NaN,25.4
15,MX17004,2010,8,tmin,NaN,NaN,NaN,NaN,15.8,NaN,...,NaN,15.0,NaN,15.6,NaN,NaN,NaN,15.3,NaN,15.4
16,MX17004,2010,10,tmax,NaN,NaN,NaN,NaN,27.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,31.2,NaN,NaN,NaN
17,MX17004,2010,10,tmin,NaN,NaN,NaN,NaN,14.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,15.0,NaN,NaN,NaN
18,MX17004,2010,11,tmax,NaN,31.3,NaN,27.2,26.3,NaN,...,NaN,NaN,NaN,NaN,28.1,27.7,NaN,NaN,NaN,NaN
19,MX17004,2010,11,tmin,NaN,16.3,NaN,12.0,7.9,NaN,...,NaN,NaN,NaN,NaN,12.1,14.2,NaN,NaN,NaN,NaN
20,MX17004,2010,12,tmax,29.9,NaN,NaN,NaN,NaN,27.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,MX17004,2010,12,tmin,13.8,NaN,NaN,NaN,NaN,10.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# Remove columns that have all NaN values:

weather = weather.dropna(axis=1, how='all')

In [5]:
# Modify the DataFrame to put the days columns as identifier variables 
# and the temperature values in one value column

weather = weather.melt(id_vars=['id', 'year', 'month', 'element'], var_name = 'day', value_name = 'temp_value')

In [6]:
# Remove the d in front of each day number

weather['day'] = weather['day'].str.extract("d(\d+)", expand=False)

In [7]:
# Remove the rows containing NaN

weather = weather.dropna(axis=0, how='any')

In [8]:
# Modify the DataFrame to have tmax and tmin as columns

weather = pd.pivot_table(weather, index=['id', 'year', 'month', 'day'], values='temp_value',columns='element')

In [9]:
weather.reset_index(inplace=True)

In [10]:
# Join columns year, month and day to have them in date format

weather['date'] = pd.to_datetime(weather[['year', 'month', 'day']])
weather = weather.drop(columns=['year', 'month', 'day'])

In [11]:
# Sort by date
weather = weather.sort_values('date')

In [12]:
# Remove column called id as the data is not relevant, 
# because all the data comes from the same station: MX17004

weather = weather.drop(columns=['id'])

In [13]:
# Display result

weather

element  tmax  tmin       date
0        27.8  14.5 2010-01-30
2        27.3  14.4 2010-02-02
4        24.1  14.4 2010-02-03
1        29.7  13.4 2010-02-11
3        29.9  10.7 2010-02-23
7        32.1  14.2 2010-03-05
5        34.5  16.8 2010-03-10
6        31.1  17.6 2010-03-16
8        36.3  16.7 2010-04-27
9        33.2  18.2 2010-05-27
10       28.0  17.5 2010-06-17
11       30.1  18.0 2010-06-29
13       28.6  17.5 2010-07-03
12       29.9  16.5 2010-07-14
19       29.6  15.8 2010-08-05
20       29.0  17.3 2010-08-08
14       29.8  16.5 2010-08-13
15       26.4  15.0 2010-08-23
16       29.7  15.6 2010-08-25
17       28.0  15.3 2010-08-29
18       25.4  15.4 2010-08-31
24       27.0  14.0 2010-10-05
25       28.1  12.9 2010-10-07
21       29.5  13.0 2010-10-14
22       28.7  10.5 2010-10-15
23       31.2  15.0 2010-10-28
26       31.3  16.3 2010-11-02
29       27.2  12.0 2010-11-04
30       26.3   7.9 2010-11-05
27       28.1  12.1 2010-11-26
28       27.7  14.2 2010-11-27
31       29.9  13.8 2010-12-01
32       27.8  10.5 2010-12-06